# Site settings
title: PJ's Blog-O-Static
email: pjhagerty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The main purpose of this blog is to try a few things and maybe document some coding experiments and whatnot.  We'll see how it goes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aspleenic.github.io" # the base hostname & protocol for your site
twitter_username: aspleenic
github_username:  aspleenic

# Build settings
markdown: kramdown
